# Generated by Django 5.0.6 on 2024-10-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_customization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Contact Us', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Connect With Us', max_length=50)),
                ('button_url', models.URLField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
