# Generated by Django 5.0.6 on 2024-12-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_customization', '0003_contactinfo_address_contactinfo_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright_text', models.CharField(default='© 2024 Your Company. All rights reserved.', max_length=255)),
                ('quick_links', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer_portfolio_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='admin_customization.footer')),
            ],
        ),
    ]
