# Generated by Django 5.0.6 on 2024-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
