# Generated by Django 5.0.6 on 2024-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_test_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
