# Generated by Django 5.0.6 on 2024-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_test_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(max_length=255),
        ),
    ]
