# Generated by Django 5.0.6 on 2025-01-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_examrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='github_link',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('CODE', 'Code-Based')], default='MCQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(help_text='Correct answer or solution'),
        ),
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='examination.answer')),
            ],
        ),
    ]
