# Generated by Django 5.0.6 on 2024-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='requiteruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
