# Generated by Django 5.0.6 on 2024-05-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0005_customuser_delete_candidateuser'),
    ]

    operations = [
    ]
