# Generated by Django 5.0.6 on 2024-05-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0007_customuser_role_candidateprofile_recruiterprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
