# Generated by Django 5.0.6 on 2025-02-21 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0013_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Unknown', help_text='Enter your full name (Each word should start with an uppercase letter).', max_length=50, validators=[django.core.validators.RegexValidator(message="Enter a valid name (Each word should start with an uppercase letter, e.g., 'John Doe').", regex='^[A-Z][a-z]*(?:\\s[A-Z][a-z]*)*$')]),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='professional_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian phone number starting with 6, 7, 8, or 9.', regex='^[6789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
