# Generated by Django 5.0.6 on 2024-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_page_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='titel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='titel_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
