# Generated by Django 5.0.6 on 2024-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_service_page_image_service_titel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('titel_description', models.TextField(blank=True, null=True)),
                ('service_page_image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_page_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='titel',
        ),
        migrations.RemoveField(
            model_name='service',
            name='titel_description',
        ),
    ]
