# Generated by Django 5.0.6 on 2024-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_page_remove_service_service_page_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_page',
            old_name='titel_description',
            new_name='page_description',
        ),
        migrations.RemoveField(
            model_name='service_page',
            name='service_page_image',
        ),
        migrations.AddField(
            model_name='service_page',
            name='service_banner_image',
            field=models.ImageField(blank=True, help_text='Upload a page banner related image', null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service_page',
            name='service_left_image',
            field=models.ImageField(blank=True, help_text='Upload a service_left related image', null=True, upload_to='service_left_images/'),
        ),
        migrations.AddField(
            model_name='service_page',
            name='service_right_image',
            field=models.ImageField(blank=True, help_text='Upload a service_right related image', null=True, upload_to='service_right_images/'),
        ),
    ]
