# Generated by Django 5.0.6 on 2024-06-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_options_remove_payment_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='candidate_username',
        ),
        migrations.AddField(
            model_name='payment',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='payment.profile'),
        ),
    ]
