# Generated by Django 5.0.6 on 2024-06-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_payment_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='payment.profile'),
        ),
    ]
