# Generated by Django 5.0.6 on 2024-06-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_payment_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI')], max_length=50),
        ),
    ]
