# Generated by Django 5.0.6 on 2024-08-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='candidate',
        ),
    ]
