# Generated by Django 5.0.6 on 2024-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_candidate_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='short_content',
            field=models.TextField(default='Default short content'),
        ),
    ]
