# Generated by Django 5.0.6 on 2024-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_subscription_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='short_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
