# Generated by Django 5.0.6 on 2024-06-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_projectexperience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexperience',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.userprofile'),
        ),
    ]
