# Generated by Django 5.0.6 on 2024-07-18 02:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
