# Generated by Django 5.0.6 on 2024-07-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexperience',
            name='project_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectexperience',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.userprofile'),
        ),
    ]
