# Generated by Django 5.0.6 on 2024-10-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, verbose_name='Social Media Platform')),
                ('link', models.URLField(max_length=500, verbose_name='Profile Link')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='profiles.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'platform')},
            },
        ),
    ]
