# Generated by Django 5.0.6 on 2025-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='education_level',
            field=models.CharField(blank=True, choices=[('10th Grade', '10th Grade'), ('12th Grade', '12th Grade'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Education Level'),
        ),
    ]
