# Generated by Django 5.0.6 on 2024-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_consultingmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the support section (e.g., TalentSprout Support)', max_length=255)),
                ('description', models.TextField(help_text='A brief description (e.g., Feel free to connect with us)')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(help_text='Support email address', max_length=254)),
                ('address', models.TextField(help_text='Physical address of the support center')),
                ('image', models.ImageField(blank=True, help_text='Upload a support-related image', null=True, upload_to='support_images/')),
            ],
        ),
        migrations.AddField(
            model_name='consultingmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a contatus related image', null=True, upload_to='contatus_images/'),
        ),
    ]
