# Generated by Django 5.0.6 on 2024-06-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_aboutuscontent_teammember_about_us_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='aboutUs.aboutuscontent'),
        ),
    ]
