# Generated by Django 5.0.6 on 2024-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0007_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
