# Generated by Django 5.0.6 on 2024-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0008_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_costing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
