# Generated by Django 5.0.6 on 2024-06-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPost', '0003_blogpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('delivery_time', models.CharField(max_length=100)),
                ('revisions', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentPost.blogpost')),
            ],
        ),
    ]
